# ä¸»é¢˜é…ç½®
## Docs: https://candinya.com/posts/Kratos-Rebirth-Manual/
## Source: https://github.com/Candinya/Kratos-Rebirth/wiki

# Global å…¨å±€é…ç½®
site_analytics: 
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: https://avatars.githubusercontent.com/SuiteLHY
snow: true
enable_dark: true
highlight_theme: night-eighties # ä»£ç é«˜äº®ä¸»é¢˜ï¼ˆlight | night | night-eighties | night-blue | night-brightï¼‰
cdn: false
check_update: false

# Index é¦–é¡µé…ç½®
index:
  post_type: false
  read_count: true
  comment_count: true

# Top Menu é¡¶éƒ¨å¯¼èˆªæ é…ç½® ï¼ˆå…·ä½“æ ¼å¼è¯·å‚ç…§æ–‡æ¡£ï¼‰
menu:
  index: /
  archives: /archives/
  friends: /friends/
  sites:
    submenu: true
    author: https://github.com/SuiteLHY
    project: https://github.com/SuiteLHY/SuiteLHY.github.io

label:
  index: <i class="fa fa-home"></i>é¦–é¡µ
  archives: <i class="fa fa-file"></i>æ¡£æ¡ˆé¦†
  friends: <i class="fa fa-paw"></i>å¥½ä¼™ä¼´
  sites:
    submenu: <i class="fa fa-link"></i>é“¾æ¥
    author: æœ¬ç«™ä½œè€…
    project: é¡¹ç›®é“¾æ¥

# Footer é¡µè„šé…ç½®
group_link: 
contact:
  weibo: 
  mail:
  telegram: SuiteLHY
  twitter: 
  facebook: 
  linkedin: 
  fediverse:
#    instance: nya.one
    instance:
#    username: Candinya
    username:
  github: SuiteLHY
  rss:
timenotice: æœ¬ç«™å·²è¿è¡Œ
icp: 
psr:

# Post Page æ–‡ç« é¡µé…ç½®
posts:
  show_cc: true
  donate: false
  share: true
  comments: valine

# Disqus [Disqus](https://disqus.com) è¯„è®ºç›¸å…³
disqus:
  shortname: 

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) è¯„è®ºç›¸å…³
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) è¯„è®ºç›¸å…³
valine:
  app_id: 0R1Qrkfq3Hl2WSuluSWjwYt3-gzGzoHsz
  app_key: PvUtUxjAQYl2GWAS6m5qYyXh
  visitor: true
  enableQQ: true

# Twikoo [Twikoo](https://twikoo.js.org) è¯„è®ºç›¸å…³
twikoo:
  env_id: 

# Waline [Waline](https://waline.js.org) è¯„è®ºç›¸å…³
## ä¸ä»…é™äºä»¥ä¸‹å†…å®¹ï¼Œæ‚¨å¯ä»¥å‚ç…§ Walineçš„ [å‰ç«¯é…ç½®æ–‡æ¡£](https://waline.js.org/client/basic.html) è®¾ç½®æ‚¨éœ€è¦çš„é…ç½®é¡¹
## el å’Œ path ä¼šåœ¨é¡µé¢è‡ªåŠ¨ç”Ÿæˆï¼Œä¸å¿…åŠ å…¥
waline:
  serverURL: #åç«¯æœåŠ¡å™¨åœ°å€ï¼Œå¿…å¡«
  visitor: true

# APlayer å·¦ä¸‹è§’éŸ³ä¹æ’­æ”¾å™¨
aplayer:
  enabled: true
  playlist: 
  meting:
    server: netease
    type: playlist
#    id: 3204190542
    id: 900328786
  order: random

# Widgets ä¾§è¾¹æ å°æŒ‚ä»¶
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
#avatarUri: /images/avatar.webp
avatarUri: https://avatars.githubusercontent.com/SuiteLHY

# Fancybox æ–‡ç« å†…å›¾ç‰‡å•å‡»æ”¾å¤§
fancybox: true

# Search æœç´¢
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript ç›¸å…³é…ç½®
## ç”±äº Javascript è¢«å‹ç¼©åéš¾ä»¥æœ‰æ•ˆç¼–è¾‘ä¸ç”Ÿæˆï¼Œå› è€Œä¸ºäº†ç®€åŒ–æ“ä½œï¼Œå°†ç›¸å…³çš„é…ç½®é¡¹åœ¨ç”Ÿæˆæ–‡ä»¶æ—¶ä»¥ç‹¬ç«‹çš„ json æ–‡ä»¶å†™å‡ºï¼Œè°ƒç”¨æ—¶ä½¿ç”¨ fetch API è·å–ã€‚
jsconfig:
  main:
    pic:
      CDN: false # è¡¨ç¤ºä¸ä½¿ç”¨CDNåŠ è½½å›¾ç‰‡
      # æ³¨æ„ï¼šå¦‚æœ"random_amount"é…ç½®é¡¹çš„å€¼å¤§äºéšæœºå›¾ç‰‡çš„æ•°é‡ï¼Œåˆ™ä¼šåœ¨ç«™ç‚¹è¿è¡Œæ—¶å‡ºç°æ‰¾ä¸åˆ°å›¾ç‰‡çš„æ˜¾ç¤ºé—®é¢˜
      random_amount: 107 # è¡¨ç¤ºä»1~107
      # å¦‚æœåŒ…å«<code>//</code>è¡¨ç¤ºä½¿ç”¨æŒ‡å®šåŸŸåçš„ç»å¯¹è·¯å¾„ï¼ˆä¾‹å¦‚ç¬¬ä¸‰æ–¹å›¾åºŠæœåŠ¡ç­‰ï¼‰ï¼Œæ­¤æ—¶ä¼šå¿½ç•¥CDNé…ç½®é¡¹
      filename: "images/thumb/thumb_{no}.webp" # ç›¸å¯¹äºä¸»é¢˜æ ¹ç›®å½•ï¼Œè¡¨ç¤ºæ–‡ä»¶åçš„æ ¼å¼ï¼Œ{no}ç”¨ä»¥æŒ‡ä»£éšæœºçš„ç¼–å·ã€‚
    createTime: "2021/04/06 20:29:04"
    donateBtn: "æ”¯æŒæˆ‘~"
    scanNotice: "æ‰«ä¸€æ‰«ï¼Œå¥½ä¸å¥½ï¼Ÿ"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: false
    leaveTitle: "{{{(>_<)}}}å“¦å“Ÿï¼Œå´©æºƒå•¦~"
    returnTitle: "(*Â´âˆ‡ï½€*)æ¬¸ï¼Œåˆå¥½å•¦~"
    copyrightNotice: "è¯¥å†…å®¹é‡‡ç”¨ CC BY-NC-SA 4.0 è®¸å¯åè®®ï¼Œè‘—ä½œæƒå½’ä½œè€…æ‰€æœ‰ã€‚å•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒï¼Œéå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚"
    expire_day: 30

# Site verify ç«™ç‚¹éªŒè¯ç›¸å…³é…ç½®å†…å®¹
site_verify:
  google: bZE7nUm9TG8--G23eE_vpUfb898ld93qzKhP7On5QRw
  baidu: 
  bing: 

# Friends å‹é“¾ç›¸å…³å†…å®¹
friends:
  href: "friends"
  page:
    title: "å¥½ä¼™ä¼´ä»¬"
    comments: true # Default false
    description: "å°ä¼™ä¼´ä»¬å¼€é¥­å•¦~"
    updated: "2021-04-07"
  list:
  - name: "Candinya"
    bio: "æœ¬ç«™å¼€æºä¸»é¢˜&thinsp;Kratos-Rebirth&thinsp;çš„ä½œè€…ğŸ­"
    avatar: "https://avatars.githubusercontent.com/Candinya"
    link: "https://candinya.com/"
  - name: "Cirnop"
    bio: "â‘¨"
    avatar: "https://avatars.githubusercontent.com/Cirnop"
    link: "https://github.com/Cirnop"
